name: av_player_android
description: Android implementation of the av_player plugin.
version: 0.2.0-beta.1
homepage: https://github.com/FlutterPlaza/av_player
repository: https://github.com/FlutterPlaza/av_player/tree/main/av_player_android

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    implements: av_player
    platforms:
      android:
        package: com.flutterplaza.avplayer
        pluginClass: AvPlayerPlugin
        dartPluginClass: AvPlayerAndroid

dependencies:
  flutter:
    sdk: flutter
  av_player_platform_interface:
    path: ../av_player_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0 <7.0.0"
  plugin_platform_interface: ^2.1.8
