name: av_player_web
description: Web implementation of the av_player plugin.
version: 0.2.0-beta.1
homepage: https://github.com/FlutterPlaza/av_player
repository: https://github.com/FlutterPlaza/av_player/tree/main/av_player_web

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    implements: av_player
    platforms:
      web:
        pluginClass: AvPlayerWeb
        fileName: av_player_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  av_player_platform_interface:
    path: ../av_player_platform_interface
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
