name: av_player_ios

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/av_player_ios.yaml"
      - "av_player_ios/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/av_player_ios.yaml"
      - "av_player_ios/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
        working-directory: av_player_ios
      - run: dart format --set-exit-if-changed .
        working-directory: av_player_ios
      - run: dart analyze --fatal-infos
        working-directory: av_player_ios
      - run: flutter test
        working-directory: av_player_ios
