name: av_player

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/av_player.yaml"
      - "av_player/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/av_player.yaml"
      - "av_player/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
        working-directory: av_player
      - run: dart format --set-exit-if-changed .
        working-directory: av_player
      - run: dart analyze --fatal-infos
        working-directory: av_player
      - run: flutter test
        working-directory: av_player
